# Generated by Django 5.2.13 on 2026-04-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_event_t_6c35be_idx',
            old_name='apps_analyt_event_t_cc5f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_visitor_cc66fd_idx',
            old_name='apps_analyt_visitor_935d66_idx',
        ),
    ]
